spring:
  application:
    name: osb-elasticsearch

---
### General Information ###
info:
  app:
    name: Elasticsearch Service Broker
    description: Elasticsearch Service Broker for Cloud Foundry Service Deployments
    version: 1.2.0

spring:
  profiles: local
  ### General Information ###
  application:
      name: osb-elasticsearch
  ### Security ###
  ssl:
    acceptselfsigned: true
  ### Cloud Config ###
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8081}
  rabbitmq:
    virtual-host: evoila

server:
  port: ${SERVER_PORT:8080}

### Logging ###
logging:
  file: ${LOG_FILE:cf-service-broker-elasticsearch.log}
  level:
    root: ${LOG_LEVEL_ROOT:INFO}

---
spring:
  profiles: pcf
  rabbitmq:
    host: "${RABBITMQ_HOST}"
  data:
    mongodb:
      host: "${MONGODB_HOST}"
haproxy:
  uri: "https://${HAPROXY-AGENT_HOST}/agents/${HAPROXY-AGENT_ID}/schemas?type=listen"