---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt
name: elasticsearch

variables:
- name: ssl_ca
  type: certificate
  options:
    is_ca: true
    common_name: elasticsearch-ssl
- name: transport_ca
  type: certificate
  options:
    is_ca: true
    common_name: elasticsearch-transport

releases:
- name: osb-bosh-elasticsearch
  version: latest
- name: osb-bosh-monitoring
  version: latest

update:
  canaries: 1
  canary_watch_time: 15000-30000
  update_watch_time: 15000-30000
  max_in_flight: 2

stemcells:
- alias: default
  os: ubuntu-trusty
  version: 3541.5

instance_groups:
- name: ingest_nodes
  instances: 0
  vm_type: default
  persistent_disk_type: small
  stemcell: default
  networks:
  - name: service
  jobs:
  - name: elasticsearch
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    provides:
      database: {as: ingest_nodes, shared: true}
  - name: smoke-tests
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: ingest_nodes}
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: elasticsearch_exporter
    release: osb-bosh-monitoring
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      node:
        allow_ingest: true
      plugins:
      - x-pack: x-pack
#      discovery:
#        minimum_master_nodes: 1 # (Number of master-eligible nodes / 2) - 1
- name: coordinating_nodes
  instances: 0
  vm_type: default
  persistent_disk_type: small
  stemcell: default
  networks:
  - name: service
  jobs:
  - name: elasticsearch
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    provides:
      database: {as: coordinating_nodes, shared: true}
  - name: smoke-tests
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: coordinating_nodes}
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: elasticsearch_exporter
    release: osb-bosh-monitoring
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      plugins:
      - x-pack: x-pack
#      discovery:
#        minimum_master_nodes: 1 # (Number of master-eligible nodes / 2) - 1
- name: master_eligible_nodes
  instances: 0
  vm_type: default
  persistent_disk_type: small
  stemcell: default
  networks:
  - name: service
  jobs:
  - name: elasticsearch
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    provides:
      database: {as: master_eligible_nodes}
  - name: smoke-tests
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: master_eligible_nodes}
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: elasticsearch_exporter
    release: osb-bosh-monitoring
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      node:
        allow_master: true
      plugins:
      - x-pack: x-pack
#      discovery:
#        minimum_master_nodes: 1 # (Number of master-eligible nodes / 2) - 1
- name: data_nodes
  instances: 0
  vm_type: default
  persistent_disk_type: medium
  stemcell: default
  networks:
  - name: service
  jobs:
  - name: elasticsearch
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    provides:
      database: {as: data_nodes}
  - name: smoke-tests
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: data_nodes}
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: elasticsearch_exporter
    release: osb-bosh-monitoring
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      node:
        allow_data: true
      plugins:
      - x-pack: x-pack
#      discovery:
#        minimum_master_nodes: 1 # (Number of master-eligible nodes / 2) - 1
- name: general_nodes
  instances: 0
  vm_type: default
  persistent_disk_type: medium
  stemcell: default
  networks:
  - name: service
  jobs:
  - name: elasticsearch
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
    provides:
      database: {as: discovery_nodes, shared: true}
  - name: smoke-tests
    release: osb-bosh-elasticsearch
    consumes:
      database: {from: discovery_nodes}
  - name: node_exporter
    release: osb-bosh-monitoring
  - name: elasticsearch_exporter
    release: osb-bosh-monitoring
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      node:
        allow_master: true
        allow_data: true
        allow_ingest: true
      plugins:
      - x-pack: x-pack
      xpack:
        security:
          http:
            ssl:
              certificate_authorities: ((ssl_ca.certificate))
              ca_key: ((ssl_ca.private_key))
            transport:
              certificate_authorities: ((transport_ca.certificate))
              ca_key: ((transport_ca.private_key))
#      discovery:
#        minimum_master_nodes: 1 # (Number of master-eligible nodes / 2) - 1