---
# https://bosh.io/docs/cli-v2.html#deployment-mgmt

name: redis

releases:
- name: osb-redis
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-trusty

############################################################
instance_groups:
- name: elasticsearch
  instances: 1
  vm_type: default
  azs:
  - z1
  persistent_disk_type: default
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: elasticsearch
    release: osb-elasticsearch
  - name: node_exporter
    release: osb-monitoring
  - name: elasticsearch_exporter
    release: osb-monitoring
  properties:
    elasticsearch:
      cluster_name: elasticsearch-cluster
      node:
        allow_master: true
        allow_data: true